#!/bin/bash
#PBS -N absreling
#PBS -l nodes=1:ppn=64
#PBS -e e.$PBS_JOBNAME-$PBS_JOBID
#PBS -o o.$PBS_JOBNAME-$PBS_JOBID

module load hyphy/2.2.6 
DATADIR=/home/sjspielman/raw_data
cd $DATADIR

INFILE=$DATADIR/$1
CWD=/opt/hyphy-2.2.6/res/TemplateBatchFiles/
GC=1
OUTFILE=$INFILE.ABSREL

## test all branches
(echo $GC; echo "1"; echo "2"; echo $INFILE; echo "Y"; echo "2"; echo "d"; echo $OUTFILE;) | /opt/hyphy-2.2.6/HYPHYMP LIBPATH=$HYPHY_LIB_DIRECTORY $CWD/BranchSiteREL.bf

#rm *.annotated.nwk
#rm *.fit